// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaLink_API.Data;

#nullable disable

namespace PharmaLink_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250711195746_update_Cart_Order_Relationships")]
    partial class update_Cart_Order_Relationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmaLink_API.Models.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountID = 1,
                            Email = "mariem@example.com",
                            Password = "hashed_password",
                            Role = "User"
                        },
                        new
                        {
                            AccountID = 2,
                            Email = "elezaby@pharmacy.com",
                            Password = "hashed_password",
                            Role = "Pharmacy"
                        });
                });

            modelBuilder.Entity("PharmaLink_API.Models.Drug", b =>
                {
                    b.Property<int>("DrugID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugID"));

                    b.Property<string>("ActiveIngredient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraindications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosageAndAdministration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosageFormsAndStrengths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugInteractions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicationsAndUsage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SideEffects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageAndHandling")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNII")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WarningsAndCautions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DrugID");

                    b.HasIndex("UNII")
                        .IsUnique();

                    b.ToTable("Drugs");

                    b.HasData(
                        new
                        {
                            DrugID = 1,
                            ActiveIngredient = "Paracetamol",
                            Category = "Analgesic",
                            CommonName = "Panadol",
                            Contraindications = "Severe liver disease",
                            Description = "A common over-the-counter pain reliever.",
                            DosageAndAdministration = "Take 1 tablet every 6 hours as needed.",
                            DosageFormsAndStrengths = "Tablet: 500mg",
                            DrugInteractions = "May interact with alcohol and blood thinners.",
                            IndicationsAndUsage = "Used to relieve pain and reduce fever.",
                            SideEffects = "Nausea, Drowsiness",
                            StorageAndHandling = "Store in a cool, dry place below 30°C.",
                            UNII = "Y43GF64R34",
                            WarningsAndCautions = "Do not exceed 4g per day."
                        },
                        new
                        {
                            DrugID = 2,
                            ActiveIngredient = "Amoxicillin and Clavulanic acid",
                            Category = "Antibiotic",
                            CommonName = "Augmentin",
                            Contraindications = "Hypersensitivity to penicillins or clavulanate",
                            Description = "Augmentin is a combination antibiotic containing amoxicillin and clavulanate potassium.",
                            DosageAndAdministration = "500mg/125mg tablet every 8 hours or as directed by the physician.",
                            DosageFormsAndStrengths = "Tablets: 500mg/125mg, 875mg/125mg",
                            DrugInteractions = "May interact with methotrexate, anticoagulants, and oral contraceptives.",
                            IndicationsAndUsage = "Used to treat bacterial infections such as respiratory tract infections, urinary tract infections, and skin infections.",
                            SideEffects = "Diarrhea, Nausea, Rash",
                            StorageAndHandling = "Store below 25°C, protect from moisture.",
                            UNII = "25E79B5CTM",
                            WarningsAndCautions = "Use with caution in patients with liver impairment or kidney disease."
                        });
                });

            modelBuilder.Entity("PharmaLink_API.Models.DrugAlternative", b =>
                {
                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int>("AlternativeDrugId")
                        .HasColumnType("int");

                    b.HasKey("DrugId", "AlternativeDrugId");

                    b.HasIndex("AlternativeDrugId");

                    b.ToTable("DrugAlternatives");

                    b.HasData(
                        new
                        {
                            DrugId = 1,
                            AlternativeDrugId = 2
                        });
                });

            modelBuilder.Entity("PharmaLink_API.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("PharmacyId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            Address = "456 Zamalek St, Cairo",
                            OrderDate = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            PharmacyId = 1,
                            Status = "Pending",
                            TotalPrice = 175.50m,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("PharmaLink_API.Models.Order_PharmacyDrug", b =>
                {
                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("DrugId", "PharmacyId", "OrderID");

                    b.HasIndex("OrderID");

                    b.ToTable("Order_PharmacyDrug");
                });

            modelBuilder.Entity("PharmaLink_API.Models.Pharmacy", b =>
                {
                    b.Property<int>("PharmacyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PharmacyID"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("EndHour")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<TimeOnly>("StartHour")
                        .HasColumnType("time");

                    b.HasKey("PharmacyID");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Pharmacies");

                    b.HasData(
                        new
                        {
                            PharmacyID = 1,
                            AccountId = 2,
                            Address = "12 Tahrir St, Cairo",
                            Country = "Egypt",
                            EndHour = new TimeOnly(23, 0, 0),
                            Name = "El Ezaby Pharmacy",
                            Rate = 4.7999999999999998,
                            StartHour = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("PharmaLink_API.Models.PharmacyDrug", b =>
                {
                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.HasKey("PharmacyId", "DrugId");

                    b.HasIndex("DrugId");

                    b.ToTable("PharmacyDrugs");

                    b.HasData(
                        new
                        {
                            PharmacyId = 1,
                            DrugId = 1,
                            Price = 50.00m,
                            QuantityAvailable = 100
                        },
                        new
                        {
                            PharmacyId = 1,
                            DrugId = 2,
                            Price = 75.50m,
                            QuantityAvailable = 50
                        });
                });

            modelBuilder.Entity("PharmaLink_API.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserDisease")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserDrugs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            AccountId = 1,
                            Address = "123 Nile Street, Cairo",
                            Country = "Egypt",
                            DateOfBirth = new DateTime(1999, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            MobileNumber = "01012345678",
                            Name = "Mariem Sameh",
                            UserDisease = "Diabetes",
                            UserDrugs = "Metformin, Insulin"
                        });
                });

            modelBuilder.Entity("PharmaLink_API.Models.UserCart", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DrugId", "PharmacyId");

                    b.HasIndex("DrugId", "PharmacyId");

                    b.ToTable("UserCarts");
                });

            modelBuilder.Entity("PharmaLink_API.Models.UserFavoriteDrug", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DrugId");

                    b.HasIndex("DrugId");

                    b.ToTable("UserFavoriteDrugs");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DrugId = 1
                        },
                        new
                        {
                            UserId = 1,
                            DrugId = 2
                        });
                });

            modelBuilder.Entity("PharmaLink_API.Models.DrugAlternative", b =>
                {
                    b.HasOne("PharmaLink_API.Models.Drug", "AlternativeDrug")
                        .WithMany()
                        .HasForeignKey("AlternativeDrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaLink_API.Models.Drug", "Drug")
                        .WithMany("Alternatives")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlternativeDrug");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("PharmaLink_API.Models.Order", b =>
                {
                    b.HasOne("PharmaLink_API.Models.Pharmacy", "Pharmacy")
                        .WithMany("Orders")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaLink_API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pharmacy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaLink_API.Models.Order_PharmacyDrug", b =>
                {
                    b.HasOne("PharmaLink_API.Models.Order", "Order")
                        .WithMany("Order_PharmacyDrugs")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaLink_API.Models.PharmacyDrug", "PharmacyDrug")
                        .WithMany("Order_PharmacyDrugs")
                        .HasForeignKey("DrugId", "PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("PharmacyDrug");
                });

            modelBuilder.Entity("PharmaLink_API.Models.Pharmacy", b =>
                {
                    b.HasOne("PharmaLink_API.Models.Account", "Account")
                        .WithOne("Pharmacy")
                        .HasForeignKey("PharmaLink_API.Models.Pharmacy", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PharmaLink_API.Models.PharmacyDrug", b =>
                {
                    b.HasOne("PharmaLink_API.Models.Drug", "Drug")
                        .WithMany("PharmacyDrugs")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaLink_API.Models.Pharmacy", "Pharmacy")
                        .WithMany("PharmacyDrugs")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("PharmaLink_API.Models.User", b =>
                {
                    b.HasOne("PharmaLink_API.Models.Account", "Account")
                        .WithOne("User")
                        .HasForeignKey("PharmaLink_API.Models.User", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PharmaLink_API.Models.UserCart", b =>
                {
                    b.HasOne("PharmaLink_API.Models.User", "User")
                        .WithMany("UserCarts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaLink_API.Models.PharmacyDrug", "PharmacyDrug")
                        .WithMany("UserCarts")
                        .HasForeignKey("DrugId", "PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PharmacyDrug");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaLink_API.Models.UserFavoriteDrug", b =>
                {
                    b.HasOne("PharmaLink_API.Models.Drug", "Drug")
                        .WithMany("UserFavorites")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaLink_API.Models.User", "User")
                        .WithMany("UserFavorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaLink_API.Models.Account", b =>
                {
                    b.Navigation("Pharmacy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaLink_API.Models.Drug", b =>
                {
                    b.Navigation("Alternatives");

                    b.Navigation("PharmacyDrugs");

                    b.Navigation("UserFavorites");
                });

            modelBuilder.Entity("PharmaLink_API.Models.Order", b =>
                {
                    b.Navigation("Order_PharmacyDrugs");
                });

            modelBuilder.Entity("PharmaLink_API.Models.Pharmacy", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PharmacyDrugs");
                });

            modelBuilder.Entity("PharmaLink_API.Models.PharmacyDrug", b =>
                {
                    b.Navigation("Order_PharmacyDrugs");

                    b.Navigation("UserCarts");
                });

            modelBuilder.Entity("PharmaLink_API.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserCarts");

                    b.Navigation("UserFavorites");
                });
#pragma warning restore 612, 618
        }
    }
}
